package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Thursday, 25 April, 2024 1:14:34 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String reverse);
} // interface ReverseOperations
